version: 1.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: src/aws_scripts/install_dependencies
      timeout: 300
      runas: root
    - location: src/aws_scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: src/aws_scripts/stop_server
      timeout: 300
      runas: root

