version: 1.0
os: linux
files:
  - source: /src/backend/
    destination: /var/www/html/b/
  - source: /src/frontend/
    destination: /var/www/html/f/
hooks:
  BeforeInstall:
    - location: /src/aws_scripts/install_dependencies
      timeout: 300
      runas: root
    - location: /src/aws_scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /src/aws_scripts/stop_server
      timeout: 300
      runas: root

